### ISSUE TITLE
Support for nested dictionaries

### ISSUE THREAD

**Issue by Just-Insane** [Just-Insane/helm-vault#1]
Helm-Vault does not support nested dictionaries, like below:

```yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: changeme
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-production
    # Enable the HTTP01 challenge mechanism for this Issuer
    dns01:
      providers:
      # Helm-Vault fails to see anything after the list, prompting only for /spec/acme/email.
      - name: prod-cloudflare
        cloudflare:
          email: changeme
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: changeme
```
