### ISSUE TITLE
ERROR: 'Namespace' object has no attribute 'environment'

### ISSUE THREAD

**Issue by shkpk** [Just-Insane/helm-vault#59]
## Describe the bug

helm vault commands returns error
```
ERROR: 'Namespace' object has no attribute 'environment'
```

## To Reproduce

Create a value.yaml files with following
```
# Sample values.yaml.template
auth:
  adminUser: VAULT:/kv/webapp/login
  adminPassword: VAULT:/kv/webapp/password
externalDatabase:
  user: VAULT:/kv/webapp/dbuser
  database: VAULT:/kv/webapp/dbname
  password: VAULT:/kv/webapp/dbpass
```
you should have secrets at this location in vault
then run

```
export VAULT_ADDR="https://vault.internal.com/" && export VAULT_NAMESPACE="test" && export VAULT_TOKEN="xxxxxxxxx"
```

```
helm vault template ../../helm-chart-0.0.1.tgz --name test-chart --namespace test-chart -f values.yaml
```
or run
```
helm vault lint test-chart -f values.yaml
```
This returns error
```
# helm vault template ../../helm-chart-0.0.1.tgz --name test-chart --namespace test-chart -f values.yaml
ERROR: 'Namespace' object has no attribute 'environment'
```
```
# helm vault lint test-chart -f values.yaml
ERROR: 'Namespace' object has no attribute 'environment'
```
## Expected behavior

Should get secrets from vault and install helm chart.

## Environment:

 * OS: Redhat 8.5
 * Python Version= 3.7.16
 * Vault Version= Vault 1.11.5+ent
